fix(centreon-map - drawio): fix translation
centreon/drawio pull request #110
Opened 2023-09-20 15:44 UTC by Yassir-BenBOUBKER

2023-09-20 15:48 UTC, Thebarda approved these changes

2023-10-12 12:03 UTC, smau-centreon requested changes

2023-10-12 12:03 UTC, smau-centreon commented on etc/propgen/convert.js
> +            en: 'the Tab for this Container is already open!',
```suggestion
            en: 'The tab for this container is already open!',
```

2023-10-12 12:03 UTC, smau-centreon commented on etc/propgen/convert.js
> +            fr: "L'onglet pour ce conteneur est déjà ouvert!",
```suggestion
            fr: "L'onglet pour ce conteneur est déjà ouvert !",
```

2023-10-12 12:03 UTC, smau-centreon commented on etc/propgen/convert.js
> +            en: 'Create Map From Container',
```suggestion
            en: 'Create map from container',
```

2023-10-12 12:03 UTC, smau-centreon commented on etc/propgen/convert.js
> +            en: 'Edit Centreon Style',
```suggestion
            en: 'Edit Centreon style',
```

2023-10-12 12:03 UTC, smau-centreon commented on etc/propgen/convert.js
> +            en: 'Please Edit Container Data to see the contents of the container',
```suggestion
            en: 'Please edit container data to see the content of the container.',
```

2023-10-12 12:03 UTC, smau-centreon commented on etc/propgen/convert.js
> +            en: `You have unsaved changes.\nIf you proceed, all changes will be lost`,
```suggestion
            en: `You have unsaved changes.\nIf you proceed, all changes will be lost.`,
```

2023-10-12 12:03 UTC, smau-centreon commented on etc/propgen/convert.js
> +            en: 'Please Save to see the contents of the container',
```suggestion
            en: 'To be able to see the content of the container, save it.',
```

2023-10-12 12:03 UTC, smau-centreon commented on etc/propgen/convert.js
> +            fr: 'Veuillez sauvegarder pour voir le contenu du conteneur.',
```suggestion
            fr: 'Pour pouvoir voir le contenu du conteneur, sauvegardez-le.',
```

2023-10-12 12:03 UTC, smau-centreon commented on etc/propgen/convert.js
> +            en: "Sorry you can't delete The last Tab",
```suggestion
            en: "You are not allowed to close the last tab.",
```

2023-10-12 12:03 UTC, smau-centreon commented on etc/propgen/convert.js
> +            fr: 'Désolé, vous ne pouvez pas supprimer le dernier onglet',
```suggestion
            fr: 'Vous ne pouvez pas fermer le dernier onglet.',
```

2023-10-12 12:54 UTC, smau-centreon approved these changes

2023-10-12 13:03 UTC, merged